version: 0.2
env:
  variables:
    PROJECT_BUILD_IMAGE_NAME: "242906888793.dkr.ecr.us-east-1.amazonaws.com/minin-frontend2"
    PROJECT_BUILD_VERSION: "latest"
    PROJECT_BUILD_IMAGE_ENV: "-master"
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - REPOSITORY_URI=$PROJECT_BUILD_IMAGE_NAME
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - PROJECT_BUILD_IMAGE_VERSION=${COMMIT_HASH:=latest}
    - IMAGE_TAG=$PROJECT_BUILD_IMAGE_VERSION$PROJECT_BUILD_IMAGE_ENV
    - IMAGE_LATEST_TAG=$PROJECT_BUILD_VERSION$PROJECT_BUILD_IMAGE_ENV
    - DOCKER_PATH="."
  build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_LATEST_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_LATEST_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_LATEST_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"minin-frontend3","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
